### ISSUE TITLE
#11 Create database

### ISSUE THREAD

**Issue by aplinxy9plin** [aplinxy9plin/preaktum#11]
<h1>Create database with some products</h1>
<ul>
<li>Use mysql or postgreesql or clickhouse(if u want)</li>
<li>Create table in database with column: <ul><li>id</li><li>name</li><li>price</li><li>count</li></ul></li>
<li>Create 3-4 note in this table</li>
</ul>

**Comment by ghost** [comment]
24c2c2f simple database
