### ISSUE TITLE
#6 Get requests

### ISSUE THREAD

**Issue by aplinxy9plin** [aplinxy9plin/preaktum#6]
<h1>Requests</h1>
<h3>Server must to get my json data and process it.</h3>
<ul>
<li>{"type": "image","imageBase64":"sometext"}</li>
<li>{"type": "basket","products":{"id":1, "name": "some_name","price": 228, "image":"url_to_picture"},"totalPrice":1337}</li>
That's all

**Comment by aplinxy9plin** [comment]
Send some response on another request.

**Comment by ghost** [comment]
b7097c0 server with processing json data and responses
